### ISSUE TITLE
slf4j-simple dependency issues

### ISSUE THREAD

**Issue by taftster** [mailgun/mailgun-java#15]
Currently, the slf4j-simple dependency is being passed through to applications via transitive dependency resolution. It is not desirable that a library like mailgun-java includes a logging implementation directly, but should instead simply define the slf4j-api as its only dependency.

It's possible that the intention is to enable logging messages during the testing phase, which is fine. This would normally be accomplished by marking the dependency in the "test" scope.

Additionally, version 1.7.36 should ideally be migrated to the 2.x versions of slf4j-api as soon as possible. slf4j 2.x supports the Java module system introduced in Java 9 and now enforced as part of Java 17.

**Comment by dvayanu** [comment]
Hello, encountered the same issue, added mailgun dependency and our logback based slf4j logging broke. Strongly support the issue as posted by OP. Do you need a pull request with a fix?

**Comment by szagr** [comment]
@dvayanu @taftster  thanks for raising this issue!
If you can, please create a PR.
Thank you

**Comment by szagr** [comment]
Dependencies were fixed/updated in v1.0.5.
