### ISSUE TITLE
slf4j-simple should be removed from pom

### ISSUE THREAD

**Issue by taftster** [mailgun/mailgun-java#17]
Following up from #15 which was closed without the proper fix.

The slf4j-simple dependency is still in the pom.xml dependencies, as of release-1.0.5.

```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
```

The problem is that this dependency becomes part of a downstream app's dependency tree. The correct way to use slf4j is to include the slf4j-api dependency as part of your library. The slf4j-simple dependency is a logging *implementation* and adversely conflicts with other logging implementations that downstream applications include in their builds.

Please remove the slf4j-simple dependency and replace it with slf4j-api, which is proper.

**Comment by szagr** [comment]
Updated in v1.0.6

**Comment by taftster** [comment]
Confirmed. Looks good. Thank you.

**Comment by szagr** [comment]
Thank you
