### ISSUE TITLE
Add the "h:sender" parameter to solve "On Behalf Of" issue.

### ISSUE THREAD

**Issue by vkolida** [mailgun/mailgun-java#24]
Using this mailgun-java library on our project we faced the issue similar to previously described on [stackoverflow](https://stackoverflow.com/questions/28401673/removing-on-behalf-of-when-sending-mail-using-mailgun) and explained at [Mailgun Help](https://help.mailgun.com/hc/en-us/articles/360012491394-Why-do-I-see-On-Behalf-Of-in-my-email-) page.

In a nutshell, the "On Behalf Of" notation is displaying as a From address in case of the mismatch between the domain used in the Sender field (mail.foo.com) and the domain used in the From field (foo.com):
`john=foo.com@mail.foo.com <john=foo.com@mail.foo.com> on behalf of; John Smith <john@foo.com>`

To solve the issue described above we need to set the `sender` property in the email header to the `from` address.

Using the `from` field: `.from(custom value)` or `.from(EmailUtil.nameWithEmail(USER_NAME, EMAIL_FROM))`, as suggested in [already closed issue #21](https://github.com/mailgun/mailgun-java/issues/21), is not the equivalent of setting `h:sender` parameter, as it only sets the From address.

So, adding the possibility to specify the `h:sender` parameter directly does make sense, at least to solve the "On Behalf Of" issue. Also, more general approach can be considered to add additional sending options/parameters by implementing `.addParameter(String name, Object value)` and/or `.addParameters(Map<String, Object> parameters)` methods within `com.mailgun.model.message.Message.MessageBuilder` to create corresponding `com.mailgun.model.message.Message`.

The only one workaround we found is to create `CustomMailgunMessagesApi` interface by extending `com.mailgun.api.v3.MailgunMessagesApi` and overload the `sendMessage` method adding additional `h:sender` url parameter, for example: 

`public interface CustomMailgunMessagesApi extends MailgunMessagesApi {`  
 `   @RequestLine("POST /{domain}/messages?h:sender={sender}")`
 `   MessageResponse sendMessage(@Param("domain") String domain, @Param("sender") String sender, Message message);`
`}`

But that it rather a hack and we would like to avoid it on production code.

@szagr, would it be possible to extend mailgun-java library with additional sending options/parameters in the nearest release? It's quite crucial for our project, as we can keep using this handy mailgun-java library. Otherwise, having this limitation, we will have to search some alternative solutions.

**Comment by carlbradwell17** [comment]
+1 on this, it's a critical feature missing in the library. 

Thanks @vkolida for your suggestion, I have created my own CustomMailgunMessagesApi as below if it helps anyone else:

```
public interface CustomMailgunMessagesApi extends MailgunMessagesApi {
	
   @RequestLine("POST /{domain}/messages?h:sender={sender}&v:urn={urn}")
   MessageResponse sendMessage(@Param("domain") String domain, @Param("sender") String sender, @Param("urn") String urn, Message message);
   
   @RequestLine("POST /{domain}/messages?h:sender={sender}")
   MessageResponse sendMessage(@Param("domain") String domain, @Param("sender") String sender, Message message);
	   
}
```

and how to use it:

```
MessageBuilder messageBuilder = Message.builder();
		
CustomMailgunMessagesApi mailgunMessagesApi = MailgunClient.config("my_api_key").createApi(CustomMailgunMessagesApi.class);
```

Alternatively, check out Sergi Baila's net.sargue.mailgun library - these features have been available for years.

**Comment by vitalii-chornobryvyi-swi** [comment]
@vkolida, thanks for raising this issue!
Sorry for the late reply.
The mentioned functionality was updated in the new release 1.0.9.
Now you can add your own headers (and nor only) by referencing this documentation:
[Send email (sender example)](https://github.com/mailgun/mailgun-java#send-email-sender-example)
[Send email (with custom form property)](https://github.com/mailgun/mailgun-java#send-email-with-custom-form-property)

Please let us know If your issue is resolved and If we can close this ticket

**Comment by carlbradwell17** [comment]
Thanks for the new release @vitalii-chornobryvyi-swi 
I have tested the 'sender' method and used FormPropertyRequestInterceptor to add a custom parameter, both are working well.
