### ISSUE TITLE
Static initialization

### ISSUE THREAD

**Issue by milosmns** [mailgun/mailgun-java#3]
Hi,

Looking at your docs:

```java
MailgunClient.config(PRIVATE_API_KEY)
  .logLevel(Logger.Level.NONE)
  .retryer(new Retryer.Default())
  .logger(new Logger.NoOpLogger())
  .errorDecoder(new ErrorDecoder.Default())
  .options(new Request.Options(10, TimeUnit.SECONDS, 60, TimeUnit.SECONDS, true))
```

If I understand this correctly, this configuration process is changing the singleton instance of the `MailgunClient`. It becomes a problem if I need to support multiple domains and multiple API keys (i.e. provided from the same backend service to multiple projects/users)... 

### Is there a way to work around this?

Can I run this configuration step somehow in a non-static manner? For example:

```java
MailgunClient client1 = new MailgunClient()
  .config(PRIVATE_API_KEY)
  ...

MailgunClient client2 = new MailgunClient()
  .config(PRIVATE_API_KEY)
  ...
```

If not, I'm kinda forced to use `curl`/`REST` endpoints directly 😞 

### Thanks!

**Comment by szagr** [comment]
Thank you for your question.
Of course, you can create the configuration in a non-static way.
The configuration can be created even for each specific call.
Example:
```
    public MessageResponse sendMessage(String apiKey, String domain, Message message) {
        MailgunMessagesApi client = createClient(apiKey);
        return client.sendMessage(domain, message);
    }

    public MailgunMessagesApi createClient(String apiKey) {
        return MailgunClient.config(apiKey).createApi(MailgunMessagesApi.class);
    }
```
Sorry for the late reply.

**Comment by milosmns** [comment]
Great, thanks for the help!

Cheers 🍻
