### ISSUE TITLE
Getting unauthorized while adding custom header

### ISSUE THREAD

**Issue by arundaskd** [mailgun/mailgun-java#30]
While trying to add custom header using the **createApiWithRequestInterceptor** 

```
MailgunMessagesApi mailgunMessagesApi = MailgunClient.config(API_KEY)
            .createApiWithRequestInterceptor(MailgunMessagesApi.class,
                MailgunRequestInterceptor.builder()
                    .addProperty("h:X-My-Header", "my_custom_header")
                    .build()
            );
```
we get the following error (_No error when using createAPI method_)

```
feign.FeignException$Unauthorized: [401 Unauthorized] during [POST] to [https://api.mailgun.net/v3/[my_verified_domain]/messages?h%3AX-My-Header=my_custom_header] [MailgunMessagesApi#sendMessage(String,Message)]: []
        at feign.FeignException.clientErrorStatus(FeignException.java:224) ~[feign-core-12.2.jar:?]
        at feign.FeignException.errorStatus(FeignException.java:203) ~[feign-core-12.2.jar:?]
        at feign.FeignException.errorStatus(FeignException.java:194) ~[feign-core-12.2.jar:?]
        at feign.FeignException.errorStatus(FeignException.java:171) ~[feign-core-12.2.jar:?]
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-12.2.jar:?]
        at feign.ResponseHandler.decodeError(ResponseHandler.java:136) ~[feign-core-12.2.jar:?]
        at feign.ResponseHandler.handleResponse(ResponseHandler.java:70) ~[feign-core-12.2.jar:?]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-12.2.jar:?]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-12.2.jar:?]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:96) ~[feign-core-12.2.jar:?]

```
Are there any other ways to include a custom header?

_Note: Removed the domain name from the error and we are using the 1.1.1 sdk version_

**Comment by vitalii-chornobryvyi-swi** [comment]
@arundaskd, thanks for raising this issue!
Sorry for the late reply.
Based on your description you are trying to add a custom header but on the code snippet I see that you are adding form property `.addProperty("h:X-My-Header", "my_custom_header")`
If you read a Javadoc for `MailgunRequestInterceptor` you can see the description and difference
<img width="1054" alt="image" src="https://github.com/mailgun/mailgun-java/assets/127201277/950155e5-f827-404c-a9b6-b6c569075384">
Also, you can find the same here https://github.com/mailgun/mailgun-java?tab=readme-ov-file#client-configuration

So can you please try to add your custom header in this way?
```
MailgunMessagesApi mailgunMessagesApi = MailgunClient.config(API_KEY)
            .createApiWithRequestInterceptor(MailgunMessagesApi.class,
                MailgunRequestInterceptor.builder()
                    .addHeader("X-My-Header", "my_custom_header")
                    .build()
            );
```
And please let us know if everything works as expected!

**Comment by arundaskd** [comment]
@vitalii-chornobryvyi-swi There was no more error when using **addHeader**, but I couldn't find this header in the mailgun logs nor in the original email headers.
We want to add **List-Unsubscribe** header with custom value.

**Comment by vitalii-chornobryvyi-swi** [comment]
Let me clarify something. Are you expecting to see `List-Unsubscribe` header in your letter for example like on this screenshot?
<img width="1067" alt="image" src="https://github.com/mailgun/mailgun-java/assets/127201277/e058ad1e-a86d-4239-a9ac-eee5fed943ba">

If I understand correctly, then can you please do like this
<img width="1113" alt="image" src="https://github.com/mailgun/mailgun-java/assets/127201277/a22f7e53-98c8-4409-a53b-6db5b9621e55">

And please let us know if everything works as expected!

**Comment by arundaskd** [comment]
@vitalii-chornobryvyi-swi Worked like charm. Thanks a lot 🙏

**Comment by vitalii-chornobryvyi-swi** [comment]
Anytime, thank you for your proactivity and communication
