### ISSUE TITLE
Customizing email headers through MailgunRequestInterceptor doesn't work

### ISSUE THREAD

**Issue by bin0234** [mailgun/mailgun-java#31]
Hi,

I noticed that the readme provides a method to add email headers through MailgunRequestInterceptor. Your example code is as follows:

```java
        MailgunMessagesApi mailgunMessagesApi = MailgunClient.config(API_KEY)
            .createApiWithRequestInterceptor(MailgunMessagesApi.class,
                MailgunRequestInterceptor.builder()
                    .addProperty("h:List-Unsubscribe", "<example@example.com>")
                    .build()
            );
```

But in actual usage, I found that the parameters added through addProperty appear in the request URL, not the request body. This resulted in an HTTP 401 response from the MailGun API. So, I implemented a request body by parsing the original request body and adding parameters to it. The code is not written elegantly :) just a demo that let you know what i mean.

```java
public class ListUnsubscribeInterceptor implements RequestInterceptor {

    private final String CRLF = "\r\n";

    @Override
    public void apply(RequestTemplate template) {
        Request request = template.request();
        byte[] body = request.body();
        String bodyStr = new String(body, StandardCharsets.UTF_8);
        String boundary = extractBoundary(bodyStr);
        StringBuffer buffer = new StringBuffer(boundary)
                .append(CRLF)
                .append("Content-Disposition: form-data; name=\"h:List-Unsubscribe\"")
                .append(CRLF)
                .append("Content-Type: text/plain; charset=UTF-8")
                .append(CRLF)
                .append(CRLF)
                .append("<example@example.com>")
                .append(CRLF)
                .append(bodyStr);

        String string = buffer.toString();
        template.body(Request.Body.create(string));
        log.info("new body:{}", new String(template.request().body(), StandardCharsets.UTF_8));
    }

    private static String extractBoundary(String input) {
        int endOfFirstLine = input.indexOf("\r\n");
        if (endOfFirstLine != -1) {
            return input.substring(0, endOfFirstLine).trim();
        } else {
            return null;
        }
    }
}

```
Is this a bug, or am I using MailgunRequestInterceptor incorrectly? Looking forward to your response.

Best,

**Comment by vitalii-chornobryvyi-swi** [comment]
@bin0234, thanks for raising this issue!
Can you please review these comments https://github.com/mailgun/mailgun-java/issues/30 and please try to apply them to your case?
After that, please let us know if everything works as expected!

**Comment by bin0234** [comment]
@vitalii-chornobryvyi-swi  Thank you very much for your help. I tried the example in [#30](https://github.com/mailgun/mailgun-java/issues/30) again, and now everything seems to be working fine! The HTTP 401 error has also been eliminated. However, I'm curious about how this 401 error disappeared. Did Mailgun's HTTP server make some changes? (Because I still see custom mail header parameters appearing in the URL rather than the request body).

**Comment by vitalii-chornobryvyi-swi** [comment]
@bin0234 I'm glad that the issue was resolved and no, Mailgun's HTTP server didn't have any changes. I just checked the request and don't see any extra info in the URL. MailgunRequestInterceptor provides one header and one form property 'h:List-Unsubscribe'  or maybe I didn't get your question. 
![image](https://github.com/mailgun/mailgun-java/assets/127201277/30a74188-2b8e-4bae-8a30-9b278ac60cc3)

Also, since the issue was resolved I'm going to close it

**Comment by bin0234** [comment]
hi @vitalii-chornobryvyi-swi ,
when i send mail by mailgun api,I can see a send log.i notice that MailgunRequestInterceptor append the parameter in url. 
<img width="875" alt="image" src="https://github.com/mailgun/mailgun-java/assets/47016825/c31dcbb0-99ab-47f0-81e6-d60278072581">
[MailgunMessagesApi#sendMessage]

**Comment by vitalii-chornobryvyi-swi** [comment]
> hi @vitalii-chornobryvyi-swi , when i send mail by mailgun api,I can see a send log.i notice that MailgunRequestInterceptor append the parameter in url. <img alt="image" width="875" src="https://private-user-images.githubusercontent.com/47016825/294183840-c31dcbb0-99ab-47f0-81e6-d60278072581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDQyMzAsIm5iZiI6MTcwNDQ0MzkzMCwicGF0aCI6Ii80NzAxNjgyNS8yOTQxODM4NDAtYzMxZGNiYjAtOTlhYi00N2YwLTgxZTYtZDYwMjc4MDcyNTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4Mzg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOWZiMDQ2ZjE5ZjVmMWViYzQyOWE5ZTQyYTY4ZjUyYmQ1OGM2ZDk4NmU4ZDJkMjIxMmJkNjY0ZDhiNDg3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3AgNxG3buSwhR5d-Dc2p4vEjRuvD_A8G7dyOdEM8m0g"> [MailgunMessagesApi#sendMessage]

@bin0234 got your point, will look at it, thank you
