### ISSUE TITLE
Authentication when using createApiWithRequestInterceptor method

### ISSUE THREAD

**Issue by carlbradwell17** [mailgun/mailgun-java#34]
Hi,

When using the createApiWithRequestInterceptor() method, the requests are not authenticated.

E.g.  a standard call works OK:

```
MailgunMessagesApi mailgunMessagesApi = MailgunClient.config(Constants.MAILGUN_APIKEY_PRIVATE)
		.createApi(MailgunMessagesApi.class);
```
But if we use the createApiWithRequestInterceptor() method as per the documentation to add a custom property:
```
MailgunMessagesApi mailgunMessagesApi = MailgunClient.config(Constants.MAILGUN_APIKEY_PRIVATE)				
	            .createApiWithRequestInterceptor(MailgunMessagesApi.class,
	                MailgunRequestInterceptor.builder()
	                    .addProperty("h:X-My-Header", "my_custom_header")
	                    .build()
	            );
```
This will result in a HTTP 401 response, as the Authorisation header is not set.

**Comment by vitalii-chornobryvyi-swi** [comment]
@carlbradwell17 , thanks for raising this issue!
Can you please review these comments https://github.com/mailgun/mailgun-java/issues/30 and please try to apply them to your case?
After that, please let us know if everything works as expected!

**Comment by carlbradwell17** [comment]
Hi,

Following the comments, simply adding  `.addHeader("Accept" "*/*")` also works in my case.

**Comment by vitalii-chornobryvyi-swi** [comment]
Nice to hear, closing an issue
