### ISSUE TITLE
Mystery com.mailgun.MyClass

### ISSUE THREAD

**Issue by jamesreprise** [mailgun/mailgun-java#38]
There's an odd class in the root com.mailgun package called 'MyClass' in v1.1.2.

I think this ought not to be packaged in the distribution jar.

**Comment by vitalii-chornobryvyi-swi** [comment]
Thanks @jamesreprise for your finding, going to remove it

**Comment by vitalii-chornobryvyi-swi** [comment]
cleaned up a jar in the 1.1.3 version
